 
$images = [
    ['url' => 'https://cdn.ethancopping.com/codepen/Responsive%20Gallery/01.jpg', 'class' => 'tall'],
    ['url' => 'https://cdn.ethancopping.com/codepen/Responsive%20Gallery/02.jpg', 'class' => 'wide'],
    ['url' => 'https://cdn.ethancopping.com/codepen/Responsive%20Gallery/03.jpg', 'class' => ''],
    ['url' => 'https://cdn.ethancopping.com/codepen/Responsive%20Gallery/04.jpg', 'class' => 'xl-wide'],
    ['url' => 'https://cdn.ethancopping.com/codepen/Responsive%20Gallery/05.jpg', 'class' => 'tall'],
    ['url' => 'https://cdn.ethancopping.com/codepen/Responsive%20Gallery/06.jpg', 'class' => 'wide'],
    ['url' => 'https://cdn.ethancopping.com/codepen/Responsive%20Gallery/07.jpg', 'class' => ''],
    ['url' => 'https://cdn.ethancopping.com/codepen/Responsive%20Gallery/08.jpg', 'class' => 'xl-wide'],
    ['url' => 'https://cdn.ethancopping.com/codepen/Responsive%20Gallery/09.jpg', 'class' => 'tall'],
    ['url' => 'https://cdn.ethancopping.com/codepen/Responsive%20Gallery/10.jpg', 'class' => 'wide'],
    ['url' => 'https://cdn.ethancopping.com/codepen/Responsive%20Gallery/11.jpg', 'class' => ''],
    ['url' => 'https://cdn.ethancopping.com/codepen/Responsive%20Gallery/12.jpg', 'class' => 'xl-wide'],
    ['url' => 'https://cdn.ethancopping.com/codepen/Responsive%20Gallery/13.jpg', 'class' => 'tall'],
    ['url' => 'https://cdn.ethancopping.com/codepen/Responsive%20Gallery/14.jpg', 'class' => 'wide'],
    ['url' => 'https://cdn.ethancopping.com/codepen/Responsive%20Gallery/15.jpg', 'class' => ''],
    ['url' => 'https://cdn.ethancopping.com/codepen/Responsive%20Gallery/16.jpg', 'class' => 'xl-wide'],
    ['url' => 'https://cdn.ethancopping.com/codepen/Responsive%20Gallery/17.jpg', 'class' => 'tall'],
    ['url' => 'https://cdn.ethancopping.com/codepen/Responsive%20Gallery/18.jpg', 'class' => 'wide'],
    ['url' => 'https://cdn.ethancopping.com/codepen/Responsive%20Gallery/19.jpg', 'class' => ''],
    ['url' => 'https://cdn.ethancopping.com/codepen/Responsive%20Gallery/20.jpg', 'class' => 'xl-wide'],
    ['url' => 'https://cdn.ethancopping.com/codepen/Responsive%20Gallery/21.jpg', 'class' => 'tall'],
    ['url' => 'https://cdn.ethancopping.com/codepen/Responsive%20Gallery/22.jpg', 'class' => 'wide'],
    ['url' => 'https://cdn.ethancopping.com/codepen/Responsive%20Gallery/23.jpg', 'class' => ''],
    ['url' => 'https://cdn.ethancopping.com/codepen/Responsive%20Gallery/24.jpg', 'class' => 'xl-wide'],
    ['url' => 'https://cdn.ethancopping.com/codepen/Responsive%20Gallery/25.jpg', 'class' => 'tall'],
    ['url' => 'https://cdn.ethancopping.com/codepen/Responsive%20Gallery/26.jpg', 'class' => 'wide'],
    ['url' => 'https://cdn.ethancopping.com/codepen/Responsive%20Gallery/27.jpg', 'class' => ''],
    ['url' => 'https://cdn.ethancopping.com/codepen/Responsive%20Gallery/28.jpg', 'class' => 'xl-wide'],
    ['url' => 'https://cdn.ethancopping.com/codepen/Responsive%20Gallery/29.jpg', 'class' => 'tall'],
    ['url' => 'https://cdn.ethancopping.com/codepen/Responsive%20Gallery/30.jpg', 'class' => 'wide'],
];

shuffle($images);
